### ISSUE TITLE
Can I get Upload or Download progress?

### ISSUE THREAD

**Issue by henry4343** [valentinradu/WhiteRaccoon#11]
Can you help me get progress when I access file?

Thanks~

**Comment by AntonioDap** [comment]
I added file WhiteRaccon.h and WhiteRaccon.m in my project tabbed project but my build failed because:
ARC restriction
semantic issue
apple LLVM compiler 3.1 error
I'm principiant developer=( 
help for meeeee=)

**Comment by valentinradu** [comment]
Regarding the ARC problem, it didn't used to have support for it in the past. That was changed with the last commit. Regarding, the progress, you could try to listen for the `receivedData` 

`[downloadFile addObserver:self forKeyPath:@"receivedData" options:NSKeyValueObservingOptionNew context:nil];`
