### ISSUE TITLE
issue with username with @ symbol

### ISSUE THREAD

**Issue by pavlog** [valentinradu/WhiteRaccoon#12]
In some cases (shared hosting) you allowed create ftp accounts with @ in user name like: "user@host.com"

Current implementation does not work correct with usernames with such symbols

I found that using
    CFReadStreamSetProperty(readStreamRef,kCFStreamPropertyFTPUserName,self.username);
    CFReadStreamSetProperty(readStreamRef,kCFStreamPropertyFTPPassword,self.password);
will do the job correct
but you need strip username and password from fullURL property.
CFReadStreamRef readStreamRef = CFReadStreamCreateWithFTPURL(NULL, (CFURLRef)self.fullURL);

Thanks.

**Comment by valentinradu** [comment]
I know of this issue, you should try to replace @ with +.
