### ISSUE TITLE
Unknown Error!

### ISSUE THREAD

**Issue by joelrb** [valentinradu/WhiteRaccoon#14]
2013-03-12 16:29:11.309 AlertUpload[4730:c07] -[WRRequestListDirectory stream:handleEvent:] [Line 976] Unknown error!

So, how do we fix an unknown error??

**Comment by mobdevric** [comment]
same problem here.. -[WRRequestListDirectory stream:handleEvent:] [Line 980] Unknown error! kind of stuck

**Comment by valentinradu** [comment]
The last version should not give that error. Which version are you using? If you're using the last version and still get that, then, add a breakpoint into `WRRequestError` 's `message` method and print out `self.errorCode`. With the error code, I'll be able to tell you what went wrong.

**Comment by radeeccles** [comment]
This is still an issue and the steps above to set a breakpoint are useless.  The error is "Unknown"

**Comment by wimcNilesh** [comment]
Hi valentinradu I am also getting the same unknown error
case NSStreamEventErrorOccurred: {
            self.error = [[WRRequestError alloc] init];
            self.error.errorCode = [self.error errorCodeWithError:[theStream streamError]];
             InfoLog(@"code:%d",self.error.errorCode);
            InfoLog(@"%@", self.error.message);
}

I have logged the result
2014-08-01 19:25:50.924 ImageX[1313:60b] -[WRRequestListDirectory stream:handleEvent:] [Line 947] code:0
2014-08-01 19:25:50.926 ImageX[1313:60b] -[WRRequestListDirectory stream:handleEvent:] [Line 948] Unknown error!

**Comment by kpragati** [comment]
Hi I am using White Raccoon for uploading file But I got "[WRRequestListDirectory stream:handleEvent:] [Line 982] Unknown error!" this error. Can you please guide me how to remove that error. thank you.
