### ISSUE TITLE
Couldn't build WhiteRaccoon for Device 4.3.5

### ISSUE THREAD

**Issue by vasudeivendran** [valentinradu/WhiteRaccoon#2]
Thanks I have checked out your code  ,it is working fine in simulator. where as i have tried to build @ device ,it through error. any thing i need to specific for device??

Error @ device ,.m file upload & download implementation classes through streamInfo & didManagedToOpenStream are undeclared . but same code Working fine in simulator.please provide some solution for this issue

**Comment by valentinradu** [comment]
Hello, will have a look over it this weekend. Thanks for letting me know.

**Comment by valentinradu** [comment]
You can pull the latest version, it should work now. Let me know if it doesn't
