### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by grom24h** [valentinradu/WhiteRaccoon#3]
Thanks for you great ftp class.
Everything works fine, but sometimes i receive NSInvalidArgumentException error on line 484 when downloading zip file from ftp

```
    case NSStreamEventEndEncountered: {
        [self.delegate requestCompleted:self]; 
        [self destroy]; <---- HERE
    } break;
```

**Comment by grom24h** [comment]
Sorry, this is my fault.
downloadFile is a retain property in my code and in requestCompleted delegate i release it because i want to decrease app memory usage. But after [self.delegate requestCompleted:self]; there is some cleanup stuff with this object.

**Comment by valentinradu** [comment]
Hello jgrom,

I usually keep a ivar reference to whiteraccoon and dealloc it in my dealloc method. Also, to keep memory down,  you should always purge `receivedData` after you used it. (by default it persists)
