### ISSUE TITLE
Unknown error on file download

### ISSUE THREAD

**Issue by mahadevans87** [valentinradu/WhiteRaccoon#5]
Hi,

I'm trying to use your ftp library to download a file from a remote server. I have setup the download process exactly as in your readme file. But I get the following error

-[WRRequestDownload stream:handleEvent:] [Line 480] Unknown error!

My password has an '@' symbol. Therefore I encode it to %40 on sending the request.

Thanks

**Comment by valentinradu** [comment]
Well, can you try it without the "@" in it? See if that's the problem. Also, try to connect with another client, like Filezilla, see if it works.

**Comment by mahadevans87** [comment]
Unfortunately I cannot change the password since it's not under my control. I debugged the code and used the fullURLString that you build onto my browser and it works properly. Am I missing anything?

**Comment by crono81** [comment]
You can try with escaping the password with
CFURLCreateStringByAddingPercentEscapes
or
stringByAddingPercentEscapesUsingEncoding
or some other escape methods

**Comment by valentinradu** [comment]
You can try and replace @ with +. It seems that worked for some people.
