### ISSUE TITLE
Can you post updated code for ARC compliance?

### ISSUE THREAD

**Issue by asuhockey04** [valentinradu/WhiteRaccoon#6]

**Comment by kayzee** [comment]
Any chance you plan on upgrading this for ARC compliance?

**Comment by ghost** [comment]
I try to convert and re-build the project with success...
Variables are returning null ...
If you want to see, contact me so I can send you the compiled source...

**Comment by valentinradu** [comment]
It's now ARC ready. It took me a while, I admit it :)
