### ISSUE TITLE
WhiteRaccoon and Objective-C ARC

### ISSUE THREAD

**Issue by ghost** [valentinradu/WhiteRaccoon#9]
Hello,

I'm a brazilian developer, so sory for my bad English.

I try to use your source code in my iPhone Application Project.

My project use Objective-C ARC, so I convert all your source and re-build with success.
When I call the WRRequestUpload with path, hostname, username and password, everything returns null and the upload not start.

Are you have converted this source code for ARC?
If not, its possible use a no-ARC code in ARC project?

How did you learn to use the read stream and write stream of objective-c? 
You have some link to help me? 
I tried to follow Apple's CFNetwork documents but I confess not to have understood very well.

Sorry for the inconvenience.
Thank you!

**Comment by valentinradu** [comment]
You don't need convert the code to ARC, you can compile my library without ARC and the rest of you project, with Arc support. Here's how http://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project

**Comment by qmoya** [comment]
Hi there,

Following @valentinradu's advice, I've disabled ARC for WhiteRaccoon.m.  However, when I import WhiteRaccoon.h into a controller, I get

> ARC forbids Objective-C objects in structs or unions. In file included from /Users/...Controller.m:4

What am I doing wrong?

Thanks for your help!

**Comment by fuxlud** [comment]
valentinradu, I am having the same problem.
I disabled arc for WhiteRaccoon.m, but WhiteRaccoon.h yells "ARC forbids Objective-C objects in structs or unions. In file included from /Users/...Controller.m:4"

**Comment by fuxlud** [comment]
Found a solution:
http://stackoverflow.com/a/8357620/1341180:

**ARC forbids Objective-C objects in structs or unions despite marking the file -fno-objc-arc:**

If you got this message try __unsafe_unretained. It is only safe, if the objects in the struct are unretained. Example: If you use OpenFeint with ARC the Class OFBragDelegateStrings says this error in a struct.

typedef struct OFBragDelegateStrings
{
     NSString\* prepopulatedText;
     NSString\* originalMessage;
} OFBragDelegateStrings;
to

typedef struct OFBragDelegateStrings
{
     __unsafe_unretained NSString\* prepopulatedText;
     __unsafe_unretained NSString\* originalMessage;
} OFBragDelegateStrings;

**Comment by valentinradu** [comment]
Probably to late for you guys, but WhiteRaccoon supports ARC now. Will close this issue.

**Comment by lloydsargent** [comment]
Black Raccoon has supported ARC for several months now and has moved on to add features as well. For example, rather than everything being in RAM you can now read and write to files, there are also delegates for large downloads, etc.

github.com/lloydsargent/BlackRaccoon

**Comment by valentinradu** [comment]
That's nice, I'm happy you improved it. You could have merged it back if you wanted. Anyway, for me, it's fine like this as well.  I have some future plans with it too, but I'll see how I've got the time to do them. Segmentation sure thing comes handy if you're downloading anything else but text files.
